### ISSUE TITLE
Do you have a sample implementation for a simple app with multiple screens?

### ISSUE THREAD

**Issue by arikcohen** [gaperton/ionic-views#1]
First of all -- this looks awesome and very helpful.  Secondly, I'm trying to get a basic model working and I'm confused as to the needed/expected references between modules in the overall model.

Thanks!

**Comment by gaperton** [comment]
Hi. Not yet. I might add the starting project boilerplate soon.

**Comment by gaperton** [comment]
Check the develop branch; I put the boilerplate there. Didn't try to run it on watches, but it must be enough to illustrate the idea.

**Comment by gaperton** [comment]
There's also some untested changes in `app/view.js` in the `develop` branch. I've added experimental support for the generic selectors like `#my-screen .class-name #some-id`. Again, didn't test that. That stuff seems to be cool but actually is not terribly needed.

You may try if it works, and roll back to the `master` branch version if it doesn't. Or, try to fix the bug and make the PR. I will appreciate that.

**Comment by gaperton** [comment]
Deployed the sample app to the `master` branch.
